### PR TITLE
Exclude command pushes from limits

### PR DESCRIPTION
**Pull request by JBassett**
`request_location_update` and `clear_notification` won't count against limits.
Fixes: https://github.com/home-assistant/mobile-apps-fcm-push/issues/9

### CODE REVIEW

**Comment by JBassett** [comment]
This change has already been deployed FYI.

**Comment by mdrichardson** [comment]
> This change has already been deployed FYI.

Deployed live? I'm still hitting the limits when notifying with:

```json
{
    "message": "request_location_update"
}
```

image

**Comment by mdrichardson** [comment]
@robbiet480 My `request_location_update` messages are still counting towards my rate limit. Is this change live?

**Comment by JBassett** [comment]
@mdrichardson are you sending 150 non `request_location_update`s prior to that?

**Comment by mdrichardson** [comment]
@JBassett No. I only send 3 or 4 non-`request_location_update` notifications a week. I'll turn the location requests on again and see if notifies me, again. 

This is something I shouldn't need to update the phone app for, right?

**Pull request merged**
