### PR TITLE
Changes for android channel support.

### PR DESCRIPTION
**Pull request by JBassett**
Associated with https://github.com/home-assistant/android/pull/574

### CODE REVIEW

**Comment by CraftyKoala** [comment]
Looks good, so I assume we stick with channel and I leave it as is.

**Comment by JBassett** [comment]
@robbiet480 or @balloob Any chance I can get write permission to this repository?  I have the access to deploy but not merge.

**Comment by balloob** [comment]
fixing.

**Comment by balloob** [comment]
done.

**Pull request merged**
